### ISSUE TITLE
`Vec` created in Buddy Allocator while running in protected will cause crash when calling `push()` unless creation is made by calling `with_capacity()`

### ISSUE THREAD

**Issue by raphfaur** [frozenpeach-dev/bootloader#19]

**Comment by raphfaur** [comment]
Not sure if Buddy Allocator is the culprit. Maybe caused by something else

**Comment by raphfaur** [comment]
Some elements suggest that it's a wider issue

**Comment by sleiderr** [comment]
I didn't manage to reproduce the issue on the current main branch, I ran some allocation / deallocation checks for various allocation sizes and I did not spot issues.
